runtime: python312

instance_class: F2

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app

env_variables:
  PYTHONUNBUFFERED: "1"
  # Cloud SQL Connection
  # INSTANCE_CONNECTION_NAME: "project-id:region:instance-name"
  # DB_USER: "user"
  # DB_PASS: "password"
  # DB_NAME: "database_name"

handlers:
  # Serve static files from the frontend directory
  - url: /frontend
    static_dir: frontend
    secure: always
    redirect_http_response_code: 301

  # All other requests go to the FastAPI app
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50
